VERZIJA=CDX
MODUL=rnal_sif

SRCDOSROOT=c:\\dev\\fmk\\rnal\\sif\\

PRGS=m_sif.prg articles.prg cust.prg cont.prg groups.prg add_ops.prg elements.prg ut.prg roba.prg partn.prg s_rnka.prg s_rnop.prg s_rgr.prg s_rtip.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
