VERZIJA=CDX
MODUL=rnal_sif

SRCDOSROOT=c:\\dev\\fmk\\rnal\\sif\\

PRGS=m_sif.prg cust.prg cont.prg aops.prg aops_att.prg e_groups.prg articles.prg elements.prg ut.prg roba.prg partn.prg s_rnka.prg s_rnop.prg s_rgr.prg s_rtip.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
