VERZIJA=CDX
MODUL=rnal_sif

SRCDOSROOT=c:\\dev\\fmk\\rnal\\sif\\

PRGS=m_sif.prg cust.prg cont.prg aops.prg aops_att.prg e_groups.prg articles.prg art_srch.prg elements.prg ut.prg e_gr_val.prg e_gr_att.prg lami_gen.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
