VERZIJA=CDX
MODUL=rnal_df

SRCDOSROOT=c:\\dev\\fmk\\rnal\\dok_frm\\

PRGS=ed_rnal.prg d_rnal.prg ed_rnst.prg ed_rnop.prg v_ed.prg 
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
