VERZIJA=CDX
MODUL=rnal_df

SRCDOSROOT=c:\\dev\\fmk\\rnal\\dok_frm\\

PRGS=ed_doc.prg doc_main.prg doc_item.prg doc_aop.prg fnd_par.prg 
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
