VERZIJA=CDX
MODUL=rnal_db

SRCDOSROOT=c:\\dev\\fmk\\rnal\\db\\

PRGS=db.prg m_adm.prg util.prg rnal.prg nal_log.prg nal_prom.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
