VERZIJA=CDX
MODUL=rnal_db

SRCDOSROOT=c:\\dev\\fmk\\rnal\\db\\

PRGS=db.prg m_adm.prg util.prg doc_db.prg doc_log.prg doc_ch.prg log_dam.prg rules.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
