VERZIJA=CDX
MODUL=rnal_db

SRCDOSROOT=$(BASEDOS)\\fmk\\rnal\\db\\

PRGS=db.prg m_adm.prg util.prg doc_db.prg doc_log.prg doc_ch.prg log_dam.prg rules.prg
CS=
ASMS=

include ../../fmk_lib/Makefile_clipper
