VERZIJA=CDX
MODUL=RNAL

SRCDOSROOT=$(BASEDOS)\\fmk\\rnal\\exe\\
PRGS=e.prg

CS=
ASMS=

EOBJCOPY=echo nista za kopirati
FMK_LIBS=fmk_roba.lib fmk_svi.lib fmk_evn.lib fmk_sec.lib fmk_lok.lib fmk_rn.lib fmk_rule.lib xmllib.lib fiscal.lib

SCLIB_LIBS=sc1g_arh.lib sc1g_ba.lib sc1g_cui.lib sc1g_db.lib sc1g_os.lib sc1g_ost.lib sc1g_par.lib sc1g_pr.lib sc1g_sif.lib sc1g_sql.lib sc1g_ut.lib sc2g_app.lib sc2g_db.lib sc1g_rpt.lib sc1g_key.lib sc2g_cui.lib ka_s1pf.lib sc_epl2.lib sc_gvp.lib sc1g_eml.lib

MODUL_LIBS=rnal_m.lib rnal_db.lib rnal_df.lib rnal_sif.lib rnal_par.lib rnal_ut.lib rnal_do.lib rnal_rpt.lib rnal_ex.lib 

include ../../fmk_lib/Makefile_clipper
