VERZIJA=CDX
MODUL=rnal_rpt

SRCDOSROOT=c:\\dev\\fmk\\rnal\\rpt\\

PRGS=m_rpt.prg rpt_rnal.prg r_lstnal.prg rpt_spec.prg rpt_ut.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
