VERZIJA=CDX
MODUL=rnal_rpt

SRCDOSROOT=$(BASEDOS)\\fmk\\rnal\\rpt\\

PRGS=m_rpt.prg rpt_rnal.prg r_lstnal.prg rpt_spec.prg rpt_ut.prg rpt_eml.prg rpt_pro.prg rpt_ral.prg
CS=
ASMS=

include ../../fmk_lib/Makefile_clipper
