VERZIJA=CDX
MODUL=rnal_do

SRCDOSROOT=c:\\dev\\fmk\\rnal\\dok\\

PRGS=doc_lst.prg log_lst.prg db_rnal.prg st_dok.prg nalpr.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
