VERZIJA=CDX
MODUL=rnal_do

SRCDOSROOT=c:\\dev\\fmk\\rnal\\dok\\

PRGS=m_rnal.prg lst_nal.prg lst_log.prg db_rnal.prg nalpr.prg otpr.prg st_dok.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
