VERZIJA=CDX
MODUL=rnal_do

SRCDOSROOT=$(BASEDOS)\\fmk\\rnal\\dok\\

PRGS=doc_lst.prg log_lst.prg db_rnal.prg st_dok.prg nalpr.prg obrl.prg sel_it.prg label.prg
CS=
ASMS=

include ../../fmk_lib/Makefile_clipper
